version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
        - "8080:80"
    volumes:
        - ./code:/code
        - ./volumeFiles:/code/res
        - ./hosts/site.conf:/etc/nginx/conf.d/default.conf
    links:
        - php

  php:
      build: .
      volumes:
        - ./code:/code
        - ./volumeFiles:/code/res
